using System;

namespace YggdrAshill.Nuadha.Signalization
{
    /// <summary>
    /// Generates <typeparamref name="TSignal"/> in order to send to each of <see cref="IConsumption{TSignal}"/>.
    /// </summary>
    /// <typeparam name="TSignal">
    /// Type of <see cref="ISignal"/> to transmit.
    /// </typeparam>
    /// <remarks>
    /// Should be generated by <see cref="IPropagation{TSignal}"/> combined with <see cref="IGeneration{TSignal}"/>.
    /// In detail, please see <see cref="PropagationExtension.ToTransmit{TSignal}(IPropagation{TSignal}, IGeneration{TSignal})"/>.
    /// </remarks>
    public interface ITransmission<TSignal> :
        IProduction<TSignal>,
        IEmission,
        IDisposable
        where TSignal : ISignal
    {

    }
}
